name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 1'

jobs:

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: 'Setup Neo4j with APOC'
        uses: mdanics/Setup-Neo4j@1.0.0
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: recipes/workflow.yaml
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channel-priority: true
          use-mamba: true
      - name: 'Build conda package'
        run: |
          conda-build recipes/
      - name: 'Run tests'
        run: |
          pip install --no-deps .
          python -m pytest tests

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Build with maven'
        run: |
          mvn clean package -f neo4jefmtool/pom.xml
